end-to-end-solutions/kma/src/Web UI Template/CognitiveSearch.Web/Controllers/DocumentEntitiesController.cs
using CognitiveSearch.Web.Configuration;
using CognitiveSearch.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json.Linq;
using System.Threading.Tasks;

namespace CognitiveSearch.Web.Controllers
{
    [Route("[controller]")]
    public class DocumentEntitiesController : Controller
    {
        private readonly AppConfig _appConfig;

        public DocumentEntitiesController(AppConfig appConfig)
        {
            _appConfig = appConfig;
        }

        [HttpGet]
        [HttpPost]
        public IActionResult Search(string query)
        {
            if (string.IsNullOrEmpty(query))
            {
                query = "";
            }

            var viewModel = new SearchViewModel
            {
                AppConfig = _appConfig,
                Query = query,
                SearchId = string.Empty
            };

            return View(viewModel);
        }
    }
}

end-to-end-solutions/kma/src/Web UI Template/CognitiveSearch.Web/Controllers/ImageController.cs
using CognitiveSearch.Web.Configuration;
using CognitiveSearch.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.PowerBI.Api.V2;
using Microsoft.PowerBI.Api.V2.Models;
using Microsoft.Rest;
using Newtonsoft.Json.Linq;
using System;
using System.Linq;
using System.Collections.Specialized;
using System.Diagnostics;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using System.Web;

namespace CognitiveSearch.Web.Controllers
{
    public class ImageController : Controller
    {
        public static string _accessToken;
        public PowerBIViewModel powerBIViewModel;
        private readonly AppConfig _appConfig;

        public ImageController(AppConfig appConfig)
        {
            _appConfig = appConfig;

            if (powerBIViewModel == null)
            {
                powerBIViewModel = new PowerBIViewModel();
            }
        }

        public IActionResult Index()
        {
            if (Request.Query.ContainsKey("code"))
            {
                if (_accessToken == null)
                {
                    var authCode = Request.Query["code"][0];
                    Task.Run(async () => await GetAccessToken(authCode)).Wait();
                    powerBIViewModel.AccessToken = _accessToken;
                    Task.Run(async () => await EmbedReport()).Wait();
                }
                else
                {
                    // handle refresh in web page
                    powerBIViewModel.AccessToken = _accessToken;
                    Task.Run(async () => await EmbedReport()).Wait();
                }
            }
            else
            {
                var errorMessage = VerifySettings();
                if (string.IsNullOrEmpty(errorMessage))
                {
                    GetAuthorizationCode();
                }
                else
                {
                    // error in settings
                    Response.Redirect($"Error?message={errorMessage}");
                }
            }

            return View(powerBIViewModel);
        }
        
        private async Task EmbedReport()
        {
            using (var client = new PowerBIClient(new Uri(_appConfig.Authorization.PowerBIApiUrl), new TokenCredentials(powerBIViewModel.AccessToken, "Bearer")))
            {
                var groups = await client.Groups.GetGroupsAsync();
                string groupId = groups.Value.FirstOrDefault()?.Id;

                if (string.IsNullOrEmpty(groupId))
                {
                    // no groups available for user
                    string message = "No group available, need to create a group and upload a report";
                    Response.Redirect($"Error?message={message}");
                }

                // getting first report in selected group from GetReports results
                var reports = await client.Reports.GetReportsInGroupAsync(groupId);
                Report report = reports.Value.Where(r => r.Name == "images").FirstOrDefault();

                if (report != null)
                {
                    powerBIViewModel.EmbedUrl = "https://app.powerbi.com/reportEmbed?reportId=ed4933f7-ec59-4227-8377-dc75c3e7401c&autoAuth=true&ctid=68bcc9b2-d056-4374-a62d-0ad3b5296583&config=eyJjbHVzdGVyVXJsIjoiaHR0cHM6Ly93YWJpLXNvdXRoLWVhc3QtYXNpYS1iLXByaW1hcnktcmVkaXJlY3QuYW5hbHlzaXMud2luZG93cy5uZXQvIn0%3D";
                    powerBIViewModel.ReportId = report.Id;
                }
                else
                {
                    // no reports available for user in chosen group
                    // need to upload a report or insert a specific group id in appsettings.json
                    string message = "No report available in workspace with ID " + groupId + ", Please fill a group id with existing report in appsettings.json file";
                    Response.Redirect($"Error?message={message}");
                }
            }
        }

        private void GetAuthorizationCode()
        {
            var queryParams = new NameValueCollection
            {
                // Azure AD will return an authorization code. 
                {"response_type", "code"},

                // Client ID is used by the application to identify themselves to the users that they are requesting permissions from. 
                // You get the client id when you register your Azure app.
                {"client_id", _appConfig.Authorization.ApplicationId},

                // Resource uri to the Power BI resource to be authorized
                // The resource uri is hard-coded for sample purposes
                {"resource", _appConfig.Authorization.ResourceUrl},

                // After app authenticates, Azure AD will redirect back to the web app. In this sample, Azure AD redirects back
                // to Default page (Default.aspx).
                { "redirect_uri", _appConfig.Authorization.RedirectUrl + "/Image"}
            };

            // Create sign-in query string
            var queryString = HttpUtility.ParseQueryString(string.Empty);
            queryString.Add(queryParams);

            // Redirect to Azure AD Authority
            //  Authority Uri is an Azure resource that takes a application id and application secret to get an Access token
            //  QueryString contains 
            //      response_type of "code"
            //      client_id that identifies your app in Azure AD
            //      resource which is the Power BI API resource to be authorized
            //      redirect_uri which is the uri that Azure AD will redirect back to after it authenticates

            // Redirect to Azure AD to get an authorization code
            Response.Redirect($"{_appConfig.Authorization.AuthorityUri} ?{queryString}");
        }

        private async Task GetAccessToken(string authCode)
        {
            using (var httpClient = new HttpClient())
            {
                httpClient.DefaultRequestHeaders.Add("Accept", "application/json");

                var requestBody = $"grant_type=authorization_code" +
                    $"&client_id={_appConfig.Authorization.ApplicationId}" +
                    $"&code = " + authCode +
                    $"&redirect_uri=" + _appConfig.Authorization.RedirectUrl + "/Image" +
                    $"&resource={HttpUtility.UrlEncode(_appConfig.Authorization.ResourceUrl)}" +
                    $"&client_secret={"BmE9mbqkx./I7U]@d3pWKoyUAKnazoo9"}";
                    //$"&client_secret={"xqO@.Ti00BCjOYQlzN7AF2b=A.IqWb44"}";

                using (var response = await httpClient.PostAsync(_appConfig.Authorization.LoggingRequestUrl,
                    new StringContent(requestBody, Encoding.UTF8, "application/x-www-form-urlencoded")))
                {
                    if (response.IsSuccessStatusCode)
                    {
                        var result = JObject.Parse(await response.Content.ReadAsStringAsync());
                        _accessToken = result.Value<string>("access_token");
                    }
                    else
                    {
                        Response.Redirect("Error?message=Can't get access token");
                    }
                }
            }
        }

        private string VerifySettings()
        {
            string message = null;
            Guid result;

            // Application Id must have a value.
            if (string.IsNullOrWhiteSpace(_appConfig.Authorization.ApplicationId))
            {
                message = "ApplicationId is empty. please register your application as Native app in https://dev.powerbi.com/apps and fill application Id in appsettings.json";
            }
            else
            {
                // Application Id must be a Guid object.
                if (!Guid.TryParse(_appConfig.Authorization.ApplicationId, out result))
                {
                    message = "ApplicationId must be a Guid object. please register your application as Native app in https://dev.powerbi.com/apps and fill application Id in appsettings.json";
                }
            }

            //// Workspace Id must be a Guid object.
            //if (!string.IsNullOrWhiteSpace(_appConfig.Authorization.GroupId))
            //{
            //    if (!Guid.TryParse(AppSettings.GroupId, out result))
            //    {
            //        message = "GroupId must be a Guid object. Please select a group you own and fill its Id in appsettings.json";
            //    }
            //}

            // All urls must have value
            if (string.IsNullOrWhiteSpace(_appConfig.Authorization.PowerBIApiUrl) || string.IsNullOrWhiteSpace(_appConfig.Authorization.AuthorityUri) ||
                string.IsNullOrWhiteSpace(_appConfig.Authorization.RedirectUrl) || string.IsNullOrWhiteSpace(_appConfig.Authorization.ResourceUrl) || string.IsNullOrWhiteSpace(_appConfig.Authorization.LoggingRequestUrl))
            {
                message = "One or more of the urls required are missing. Please check appsettings.json file. for more info check sample instructions in https://github.com/Microsoft/PowerBI-Developer-Samples";
            }

            return message;
        }
        //**/
    }
}

end-to-end-solutions/kma/src/Web UI Template/CognitiveSearch.Web/Controllers/QnaController.cs
using CognitiveSearch.Web.Configuration;
using CognitiveSearch.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json.Linq;
using System.Threading.Tasks;

namespace CognitiveSearch.Web.Controllers
{
    [Route("[controller]")]
    public class QnaController : Controller
    {
        private readonly AppConfig _appConfig;

        public QnaController(AppConfig appConfig)
        {
            _appConfig = appConfig;
        }

        [HttpGet]
        [HttpPost]
        public IActionResult Search(string query)
        {
            if (string.IsNullOrEmpty(query))
            {
                query = "";
            }

            var viewModel = new SearchViewModel
            {
                AppConfig = _appConfig,
                Query = query,
                SearchId = string.Empty
            };

            return View(viewModel);
        }
    }
}

end-to-end-solutions/kma/src/Web UI Template/CognitiveSearch.Web/Views/Shared/_Architecture.cshtml
<div class="row">
    <h4>Explore your files using Cognitive Search with Azure Search</h4>
</div>

<div class="row">
    <p>
        <span>To learn more, read </span>
        <a href="https://docs.microsoft.com/en-us/azure/search/cognitive-search-concept-intro" target="_blank">
            What is "cognitive search" in Azure Search?
        </a>
    </p>
    <p>
        <span>You can view and download the source code from the </span>
        <a href="//aka.ms/cog-search-starter-code">Azure Cognitive Search starter project GitHub repo</a>.
    </p>
    <p>
        Below is a basic architectural diagram that represents how cognitive search in Azure Search works:
    </p>
    <p>
        <img src="~/images/cogsearch-architecture.png" alt="Cognitive search with Azure Search" class="img" />
    </p>
    
</div>

end-to-end-solutions/kma/src/Web UI Template/CognitiveSearch.Web/Views/Shared/_Footer.cshtml
@using CognitiveSearch.Web.Configuration
@inject OrganizationConfig OrgConfig

<footer class="border-top footer text-muted fixed-bottom p-0 footer-bg footer-text">
    <div class="footer-content container-fluid">
        <div class="statement-area footer-text">
            &copy; @DateTime.Now.Year - @OrgConfig.Name
        </div>
        <div class="link-area">
            <a asp-area="" asp-action="Privacy" asp-controller="Home" class="footer-link footer-text">Privacy</a>
        </div>
    </div>
</footer>

end-to-end-solutions/kma/src/Web UI Template/CognitiveSearch.Web/Views/Shared/_Layout.cshtml
@using CognitiveSearch.Web.Configuration
@inject AppConfig AppConfig

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Petronas</title>
    <link rel="shortcut icon" type="image/png" href="~/images/favicon.jpg">

    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="https://static2.sharepointonline.com/files/fabric/office-ui-fabric-js/1.2.0/css/fabric.components.min.css" />
    <link rel="stylesheet" href="~/lib/fabric-ui/fabric.css" />
    <link rel="stylesheet" href="~/lib/fabric-ui/fabric-9.4.0.scoped.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />

    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/navbar.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/footer.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/homepage.css" asp-append-version="true" />
    @Html.Raw(JavaScriptSnippet.FullScript)
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="https://static2.sharepointonline.com/files/fabric/office-ui-fabric-js/1.2.0/js/fabric.min.js"></script>
    <script src="https://d3js.org/d3.v4.min.js"></script>
    <script src="https://d3js.org/d3-selection-multi.v1.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.min.js"></script>
    <script src="https://unpkg.com/imagesloaded@4/imagesloaded.pkgd.min.js"></script>
</head>
<body class="dark-themed" id="page-body">
    <header>
        <nav class="navbar navbar-bg border-bottom mb-3 fixed-top no-padding-navbar">
            <div class="container-fluid">

                <div class="navbar-title-container">
                    <p class="navbar-title">PETRONAS KNOWLEDGE DISCOVERY</p>
                </div>

                <div class="navbar-menu-container" id="navbar-menu-container">
                    <ul class="navbar-nav list-group-horizontal">
                        <li class="nav-item">
                            <a id="customize-page" class="nav-link navbar-text navbar-item-factoidsearch" asp-area="" asp-controller="FactoidSearch" asp-action="Index">
                                <div class="navbar-item-content">
                                    <div class="navbar-item-content-logo"></div>
                                    <div class="navbar-item-content-name">Question and Answer</div>
                                </div>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link navbar-text navbar-item-qna" asp-area="" asp-controller="Qna" asp-action="Search">
                                <div class="navbar-item-content">
                                    <div class="navbar-item-content-logo"></div>
                                    <div class="navbar-item-content-name">Machine Reading Comprehension</div>
                                </div>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a id="customize-page" class="nav-link navbar-text navbar-item-search" asp-area="" asp-controller="Search" asp-action="Search">
                                <div class="navbar-item-content">
                                    <div class="navbar-item-content-logo"></div>
                                    <div class="navbar-item-content-name">Document Search</div>
                                </div>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a id="customize-page" class="nav-link navbar-text navbar-item-documententities" asp-area="" asp-controller="DocumentEntities" asp-action="Search">
                                <div class="navbar-item-content">
                                    <div class="navbar-item-content-logo"></div>
                                    <div class="navbar-item-content-name">Document Entities</div>
                                </div>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a id="customize-page" class="nav-link navbar-text navbar-item-image" asp-area="" asp-controller="Image" asp-action="Index">
                                <div class="navbar-item-content">
                                    <div class="navbar-item-content-logo"></div>
                                    <div class="navbar-item-content-name">Image Search</div>
                                </div>
                            </a>
                            </a>
                        </li>
                    </ul>
                </div>

                <div class="navbar-logo-container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                        <img src="~/images/@AppConfig.Organization.Logo" height="60px" id="navbar-img" alt="@AppConfig.Organization.Name logo" title="@AppConfig.Organization.Name Cognitive Search" class="logo-container logo-sgv" asp-append-version="true" />
                    </a>
                </div>

            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <div class="row">
            @RenderBody()
        </div>
    </div>

    <!-- The Modal -->
    <div id="tutorial-modal" class="tutorial-modal">
        <!-- Modal content -->
        <div class="left-tutorial-modal-content" id="tutorial-modal-content">
            <p class="m-1">some text</p>
            <br />
            <span class="m-1" style="float:left;font-weight:600"><a id="previous-tut-link" href="javascript:showTutorialSection();">previous</a></span>
            <span class="m-1" style="float:left;font-weight:600"><a id="next-tut-link" href="javascript:showTutorialSection();">next</a></span>
            <span class="m-1" style="float:right;font-weight:600"><a id="skip-tut-link" href="javascript:skipTutorial(false);">Skip Tutorial</a></span>

        </div>
    </div>

    <div id="introModal" class="tutorial-intro-modal">
        <!-- Modal content -->
        <div class="tutorial-intro-modal-content">
            <h2>Tutorial</h2>
            <p>This tutorial will walk you through the key features of this demo solution. Click "Begin" to start.</p>
            <p>For more information about how to use this demo solution, watch the <a target="_blank" href="https://youtu.be/Xp8NiljMUEI">introduction video</a>.</p>
            <br />
            <div>

                <span class="m-1" style="float:left;font-weight:600">
                    <a href="javascript:showTutorialSection(0);">Begin</a>
                </span>
                <span class="m-1" style="float:right;font-weight:300">
                    <input type="checkbox" id="donotshowtutorial" checked style="transform:scale(1.5)">&nbsp;Don't show this again.
                </span>
                <span class="m-1" style="float:right;font-weight:600">
                    <a href="javascript:skipTutorial(true);">Skip Tutorial</a>&nbsp;&nbsp;
                </span>

            </div>
        </div>

    </div>

    <script>
        // Hong Yee Testing
        var pathName = window.location.pathname;
        console.log('pathName', pathName);

        var newPathName = pathName.split("/")[1];

        var lowCaseNewPathName = "home";

        if (!!newPathName) {
            lowCaseNewPathName = newPathName.toLowerCase();
            $(".navbar-menu-container").css('display', 'block');
        } else {
            $(".navbar-menu-container").css('display', 'none');
        }

        if (lowCaseNewPathName === "home") {
            document.getElementById("page-body").classList.add("home-page");
            document.getElementById("navbar-menu-container").classList.add("navbar-menu-hidden");
        } else {
            document.getElementById("page-body").classList.add(`${lowCaseNewPathName}-page`);

            var className = `navbar-item-${lowCaseNewPathName}`;

            var selectedElement = document.getElementsByClassName(className);

            selectedElement[0].classList.add("active");
        }

    </script>

    @*@await Html.PartialAsync("_Footer")*@

    <script src="~/js/tags.js" asp-append-version="true"></script>
    <script src="~/js/details.js" asp-append-version="true"></script>
    <script src="~/js/appInsights.js" asp-append-version="true"></script>
    <script src="~/js/results.js" asp-append-version="true"></script>
    <script src="~/js/facets.js" asp-append-version="true"></script>
    <script src="~/js/search.js" asp-append-version="true"></script>
    <script src="~/js/entityMap.js" asp-append-version="true"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script type="text/javascript">
        apiUrl = '@AppConfig.ApiConfig.Url';
        mrcApiUrl = '@AppConfig.ApiConfig.MrcApiUrl';
        docEntitiesApiUrl = '@AppConfig.ApiConfig.DocEntitiesApiUrl';
        widgetApiUrl = '@AppConfig.ApiConfig.WidgetApiUrl';
        customizable = '@AppConfig.Customizable';
    </script>
    @RenderSection("Scripts", required: false)
</body>
</html>